application:
  name: htmx-go
  port: 7883
  healthPath: /api/health

modules:
  task:
    - deploy/task.hcl

environments:
  staging:
    domain: staging.htmx.sacha.house
    noIndex: true
  production:
    domain: htmx.sacha.house

    modules:
      group:
        - deploy/group-production.hcl
volume:
  mountPath: /data

resources:
  cpu: 500
  memory: 512
