name: "htmx-go"
description: "https://htmx.sacha.house/ - Testing out HTMX using go and fiber to drive UI state from the server"
topics:
  - "go"
  - "go-fiber"
  - "htmx"
homepage: "https://htmx.sacha.house/"
source:
  provider: github
  namespace: "sachahjkl"
  path: "sachahjkl/htmx-go"
